import express from "express";
import { tenantMiddleware } from "./middleware/tenant";
import { authMiddleware, requireRole } from "./middleware/auth";
import authRoutes from "./routes/auth";
import roleRoutes from "./routes/roles";
import studentRoutes from "./routes/students";
import teacherRoutes from "./routes/teachers";
import classRoutes from "./routes/classes";
import attendanceRoutes from "./routes/attendance";
import gradeRoutes from "./routes/grades";
import noticeRoutes from "./routes/notices";
import paymentRoutes from "./routes/payments";
import academicYearRoutes from "./routes/academicYears";
import termRoutes from "./routes/terms";
import subjectRoutes from "./routes/subjects";
import timetableRoutes from "./routes/timetables";
import attendancesRoutes from "./routes/attendances";
import gradebookRoutes from "./routes/gradebook";
import libraryRoutes from "./routes/library";
import transportRoutes from "./routes/transport";
import inventoryRoutes from "./routes/inventory";
import eventRoutes from "./routes/events";
import disciplinaryRoutes from "./routes/disciplinary";
import healthRoutes from "./routes/health";
import hostelRoutes from "./routes/hostel";
import sportsRoutes from "./routes/sports";
import uploadRoutes from "./routes/upload";
import parentRoutes from "./routes/parent";

const app = express();
app.use(express.json());
app.use(tenantMiddleware);

app.use("/auth", authRoutes);
app.use("/roles", roleRoutes);
app.use("/students", authMiddleware, requireRole("ADMIN", "TEACHER"), studentRoutes);
app.use("/teachers", authMiddleware, requireRole("ADMIN"), teacherRoutes);
app.use("/classes", authMiddleware, requireRole("ADMIN", "TEACHER"), classRoutes);
app.use("/attendance", authMiddleware, requireRole("ADMIN", "TEACHER"), attendanceRoutes);
app.use("/grades", authMiddleware, requireRole("ADMIN", "TEACHER"), gradeRoutes);
app.use("/notices", authMiddleware, noticeRoutes);
app.use("/payments", authMiddleware, requireRole("ADMIN"), paymentRoutes);
app.use("/academic-years", academicYearRoutes);
app.use("/terms", termRoutes);
app.use("/subjects", subjectRoutes);
app.use("/timetables", timetableRoutes);
app.use("/attendances", attendancesRoutes);
app.use("/gradebook", gradebookRoutes);
app.use("/library", authMiddleware, requireRole("ADMIN", "TEACHER", "STAFF"), libraryRoutes);
app.use("/transport", authMiddleware, requireRole("ADMIN", "STAFF"), transportRoutes);
app.use("/inventory", authMiddleware, requireRole("ADMIN", "STAFF"), inventoryRoutes);
app.use("/events", authMiddleware, requireRole("ADMIN", "TEACHER"), eventRoutes);
app.use("/disciplinary", authMiddleware, requireRole("ADMIN", "PRINCIPAL", "TEACHER"), disciplinaryRoutes);
app.use("/health", authMiddleware, requireRole("ADMIN", "STAFF"), healthRoutes);
app.use("/hostel", authMiddleware, requireRole("ADMIN", "STAFF"), hostelRoutes);
app.use("/sports", authMiddleware, requireRole("ADMIN", "TEACHER"), sportsRoutes);
app.use("/upload", authMiddleware, uploadRoutes);
app.use("/parent", authMiddleware, requireRole("PARENT"), parentRoutes);
export default app;