export { CertificateService } from "./certificateService";
export { DiscussionService } from "./discussionService";
export { HundredMsService } from "./hundredMsService";
export { JitsiService } from "./jitsiService";
export { LiveClassService } from "./liveClassService";
export { QuizService } from "./quizService";
export { RecordedLessonService } from "./recordedLessonService";
export { StudentElearningService } from "./studentElearningService";
export { SubmissionService } from "./submissionService";
